Recruitifyv1
priyam-03/Recruitify pull request #12
Opened 2024-08-15 06:35 UTC by Tarik-Anowar

2024-08-15 07:33 UTC, priyam-03 requested changes
Please make these changes and commit.

2024-08-15 07:33 UTC, priyam-03 commented on backend/index.js
Please make it same as of main branch index.js file

2024-08-15 07:33 UTC, priyam-03 commented on frontend/package.json
Keep it http only

2024-08-15 07:51 UTC, Tarik-Anowar commented on frontend/package.json
ok

2024-08-15 14:05 UTC, Tarik-Anowar commented
updated the Home Page and some post related backend stuffs

2024-08-16 14:58 UTC, priyam-03 commented
Home page updated.

2024-08-16 14:59 UTC, priyam-03 commented
Home page added.

2024-08-16 14:59 UTC, merged